.PHONY: build

build:
	docker build --build-arg PYTHON_VERSION=3.5.3 -t registry.zero.rdc.li/zero/buildbot-worker:3.5.3 .
	docker build --build-arg PYTHON_VERSION=3.6.1 -t registry.zero.rdc.li/zero/buildbot-worker:3.6.1 .




